translations = {
    "Are you sure?": "Sind Sie sicher?",
    "Cancel": "Abbrechen",
    "Close": "Schließen",
    "Confirm": "Bestätigen",
    "Device settings": "Geräteeinstellungen",
    "Enter account number": "Geben Sie die Kontonummer ein",
    "Enter derivation path": "Geben Sie den Ableitungspfad ein",
    "Enter your PIN code": "Geben Sie Ihren PIN-Code ein",
    "Enter your bip-39 password:": "Geben Sie Ihr bip-39-Passwort ein:",
    "Enter your recovery phrase": "Geben Sie Ihre Wiederherstellungsphrase ein",
    "Host setttings": "Hosteinstellungen",
    "It is never stored on the device": "Es wird nie auf dem Gerät gespeichert",
    "Make a choice": "Treffen Sie eine Wahl",
    "No settings available": "Keine Einstellungen verfügbar",
    "OFF": "AUS",
    "ON": "EIN",
    "Please wait until the process is complete.": "Bitte warten Sie, bis der Vorgang abgeschlossen ist.",
    "Processing...": "Verarbeitung...",
    "QR Alert!": "QR-Warnung!",
    "Show detailed information": "Detaillierte Informationen anzeigen",
    "Something happened": "Etwas ist passiert",
    "What do you want to do?": "Was möchten Sie tun?",
    "Wipe device": "Gerät löschen",
    "Write it down and never show it to anybody.": "Schreiben Sie es auf und zeigen Sie es niemals jemandem.",
    "Your recovery phrase:": "Ihre Wiederherstellungsphrase:",
}
