translations = {
    "Are you sure?": "Are you sure?",
    "Cancel": "Cancel",
    "Close": "Close",
    "Confirm": "Confirm",
    "Confirm your PIN code": "Confirm your PIN code",
    "Choose your PIN code": "Choose your PIN code",
    "Device settings": "Device settings",
    "Do you recognize these words?": "Do you recognize these words?",
    "Error!": "Error!",
    "Enter account number": "Enter account number",
    "Enter derivation path": "Enter derivation path",
    "Enter your PIN code": "Enter your PIN code",
    "Enter your bip-39 password:": "Enter your bip-39 password:",
    "Enter your recovery phrase": "Enter your recovery phrase",
    "Host setttings": "Host settings",
    "It is never stored on the device": "It is never stored on the device",
    "Make a choice": "Make a choice",
    "No settings available": "No settings available",
    "OFF": "OFF",
    "ON": "ON",
    "Please wait until the process is complete.": "Please wait until the process is complete.",
    "Processing...": "Processing...",
    "PIN codes are different!": "PIN codes are different!",
    "Remember these words, they will stay the same on this device.": "Remember these words, they will stay the same on this device.",
    "QR Alert!": "QR Alert!",
    "Show detailed information": "Show detailed information",
    "Something happened": "Something happened",
    "What do you want to do?": "What do you want to do?",
    "Wipe device": "Wipe device",
    "Write it down and never show it to anybody.": "Write it down and never show it to anybody.",
    "Your recovery phrase:": "Your recovery phrase:",
}
